### ISSUE TITLE
Discord Bot Breaks Posting?

### ISSUE THREAD

**Issue by philip-ulrich** [LouiseMcMahon/nodebb-plugin-discord-bot#1]
Discord Bot Version: v0.0.5
NodeBB Version: v1.0.3

Expected Behavior:
- Send notifications upon post

Experienced Behavior:
- Post "stalls", posts blank, leaves post box open (but send button disabled), and receive no discord message. 

I'm working on diagnosing another issue so during the debugging process I removed all non-default plugins and issue persists. Login is valid and I don't see any indication of issues aside from the aforementioned.

**Comment by LewisMcMahon** [comment]
Thier does seem to be some kind of issue on my end also although i do not have the same symtoms. are you beings a proxy? if so can you test without it?

**Comment by LewisMcMahon** [comment]
ive pushed a  updated to npm if that fixes it please tell me and close this

**Comment by philip-ulrich** [comment]
I'm not behind a proxy. I've even taken nodebb off of cloudflares caching. I'm am behind a firewall.. but that wasn't an issue prior to 1.0.3. 

I updated, reloaded, activated, and verified settings. No more freezing.. but no messages in discord either.

**Comment by LewisMcMahon** [comment]
please check your using the correct username and password for your discord user also can you start NodeBB in dev mode and tell me if you get any errors from the plugin

**Comment by philip-ulrich** [comment]
Yeah. Login info was the first thing I checked. I'll have to do that tomorrow. I'm in the middle of migrating between environments.

**Comment by philip-ulrich** [comment]
Sorry about the delay. I've been a bit busy. Here ya go:

> This program comes with ABSOLUTELY NO WARRANTY.
> This is free software, and you are welcome to redistribute it under certain conditions.
> For the full license, please visit: http://www.gnu.org/copyleft/gpl.html
> 
> Clustering enabled: Spinning up 1 process(es).
> 
> 21/5 00:01 [8218] - verbose: \* using configuration stored in: /home/tntcarrots/nodebb/config.json
> 21/5 00:01 [8218] - info: Time: Sat May 21 2016 00:01:59 GMT-0500 (CDT)
> 21/5 00:01 [8218] - info: Initializing NodeBB v1.0.3
> 21/5 00:01 [8218] - verbose: \* using mongo store at 127.0.0.1:27017
> 21/5 00:01 [8218] - verbose: \* using themes stored in: /home/tntcarrots/nodebb/node_modules
> 21/5 00:02 [8218] - info: [database] Checking database indices.
> 21/5 00:02 [8218] - verbose: Checking dependencies for outdated modules
> 21/5 00:02 [8218] - warn: [socket.io] Clustering detected, you are advised to configure Redis as a web socket store
> 21/5 00:02 [8218] - verbose: [notifications.init] Registering jobs.
> 21/5 00:02 [8218] - info: [themes] Using theme nodebb-theme-material
> 21/5 00:02 [8218] - verbose: [plugins] Initializing plugins system
> 21/5 00:02 [8218] - verbose: [plugins] Found 2 js file(s) for plugin nodebb-theme-material
> 21/5 00:02 [8218] - verbose: [plugins] Loaded plugin: nodebb-theme-material
> 21/5 00:02 [8218] - verbose: [plugins] Found 1 css file(s) for plugin nodebb-widget-essentials
> 21/5 00:02 [8218] - verbose: [plugins] Loaded plugin: nodebb-widget-essentials
> 21/5 00:02 [8218] - verbose: [plugins] Found 1 js file(s) for plugin nodebb-rewards-essentials
> 21/5 00:02 [8218] - verbose: [plugins] Loaded plugin: nodebb-rewards-essentials
> 21/5 00:02 [8218] - verbose: [plugins] Loaded plugin: nodebb-plugin-soundpack-default
> 21/5 00:02 [8218] - verbose: [plugins] Found 1 less file(s) for plugin nodebb-plugin-mentions
> 21/5 00:02 [8218] - verbose: [plugins] Found 1 js file(s) for plugin nodebb-plugin-mentions
> 21/5 00:02 [8218] - verbose: [plugins] Loaded plugin: nodebb-plugin-mentions
> 21/5 00:02 [8218] - verbose: [plugins] Found 1 less file(s) for plugin nodvbb-plugin-markdown
> 21/5 00:02 [8218] - verbose: [plugins] Found 1 js file(s) for plugin nodvbb-plugin-markdown
> 21/5 00:02 [8218] - verbose: [plugins] Found 1 js file(s) for plugin nodvbb-plugin-markdown
> 21/5 00:02 [8218] - verbose: [plugins] Loaded plugin: nodebb-plugin-markdown
> 21/5 00:02 [8218] - verbose: [plugins] Found 1 less file(s) for plugin nodebb-plugin-emoji-extended
> 21/5 00:02 [8218] - verbose: [plugins] Found 1 js file(s) for plugin nodebb-plugin-emoji-extended
> 21/5 00:02 [8218] - verbose: [plugins] Loaded plugin: nodebb-plugin-emoji-extended
> 21/5 00:02 [8218] - verbose: [plugins] Found 1 less file(s) for plugin nodebb-plugin-composer-default
> 21/5 00:02 [8218] - verbose: [plugins] Found 11 js file(s) for plugin nodebb-plugin-composer-default
> 21/5 00:02 [8218] - verbose: [plugins] Found 1 js file(s) for plugin nodebb-plugin-composer-default
> 21/5 00:02 [8218] - verbose: [plugins] Loaded plugin: nodebb-plugin-composer-default
> 21/5 00:02 [8218] - verbose: [plugins] Loaded plugin: nodebb-plugin-emailer-mailgun
> 21/5 00:02 [8218] - verbose: [plugins] Loaded plugin: nodebb-plugin-discord-bot
> 21/5 00:02 [8218] - verbose: [plugins] Found 1 css file(s) for plugin nodebb-plugin-lightbox
> 21/5 00:02 [8218] - verbose: [plugins] Found 1 js file(s) for plugin nodebb-plugin-lightbox
> 21/5 00:02 [8218] - verbose: [plugins] Loaded plugin: nodebb-plugin-lightbox
> 21/5 00:02 [8218] - info: [plugins] Plugins OK
> 21/5 00:02 [8218] - verbose: [meta/js] 3 of 3 modules bridged
> 21/5 00:02 [8218] - verbose: [plugins] Loading templates (nodebb-theme-material)
> 21/5 00:02 [8218] - verbose: [plugins] Loading templates (nodebb-widget-essentials)
> 21/5 00:02 [8218] - verbose: [plugins] Loading templates (nodebb-plugin-markdown)
> 21/5 00:02 [8218] - verbose: [plugins] Loading templates (nodebb-plugin-emoji-extended)
> 21/5 00:02 [8218] - verbose: [plugins] Loading templates (nodebb-plugin-composer-default)
> 21/5 00:02 [8218] - verbose: [plugins] Loading templates (nodebb-plugin-emailer-mailgun)
> 21/5 00:02 [8218] - verbose: [plugins] Loading templates (nodebb-plugin-discord-bot)
> 21/5 00:02 [8218] - verbose: [meta/templates] Compiling templates
> 21/5 00:02 [8218] - verbose: [meta/templates] Successfully compiled templates.
> 21/5 00:02 [8218] - verbose: [meta/js] Minifying nodebb.min.js
> 21/5 00:02 [8218] - verbose: [meta/js] nodebb.min.js magnification complete
> 21/5 00:02 [8218] - verbose: [meta/js] Minifying acp.min.js
> 21/5 00:02 [8218] - verbose: [meta/js] acp.min.js magnification complete
> 21/5 00:02 [8218] - verbose: [meta/css] Minifying LESS/CSS
> 21/5 00:02 [8218] - verbose: [meta/css] stylesheet.css committed to disk.
> 21/5 00:02 [8218] - verbose: [meta/css] admin.css committed to disk.
> 21/5 00:02 [8218] - info: NodeBB Ready
> 21/5 00:02 [8218] - info: Enabling 'trust proxy'
> 21/5 00:02 [8218] - info: NodeBB is now listening on: 0.0.0.0:4567
> 21/5 00:02 [8218] - verbose: [sounds] Sounds OK
> 21/5 00:02 [8218] - verbose: [meta/blacklist] Loading 0 blacklist rules
> No token provided, and unable to parse 'tenc'. Using login method.
> 21/5 00:02 [8218] - verbose: [hotswap] Router with id `plugins` replaced successfully
> 21/5 00:02 [8218] - verbose: [plugins] All plugins reloaded and rerouted
> 21/5 00:02 [8218] - verbose: [hotswap] Router with id `auth` replaced successfully
> [WARNING]: Your library (1.10.4) is out of date. Please update discord.io to 1.10.5.
> 21/5 00:02 [8218] - verbose: [translator] No resource file found for en_US/markdown, using provided fallback language file
> 21/5 00:02 [8218] - warn: [socket.io] Unrecognized message: plugins.MinecraftIntegration.eventStatus
> 21/5 00:03 [8218] - warn: [socket.io] Unrecognized message: plugins.MinecraftIntegration.eventStatus
> { pid: 106,
>   uid: 1,
>   tid: 46,
>   content: 'testtest',
>   timestamp: 1463807014777,
>   reputation: 0,
>   votes: 0,
>   editor: '',
>   edited: 0,
>   deleted: 0 }
> 21/5 00:03 [8218] - error: [NodeBB Bot] encountered a problem while sending a message Unable to send messages

**Comment by LewisMcMahon** [comment]
Cn you make sure you have the channel id set correctly and the bot is in the channel etc. When nodeBB is online it should appear in the discord server listing as online.

**Comment by philip-ulrich** [comment]
Yeah. That was one of the first things I checked:
http://d.l33t.tech/1frva/5oigPsNV
http://d.l33t.tech/17XVr/tYOP3Vv1
http://d.l33t.tech/1lvkK/2HvbABm4

**Comment by LewisMcMahon** [comment]
Im not really sure what to suggest if your comfortable with node try looking at the inputs of sendMessage the send message function.

**Comment by philip-ulrich** [comment]
Turns out I was derping. I found the line that displays the error and saw that the error it was mentioning was just the last portion "Unable to send messages". A quick bit of logic lead me to check the role for the bot which made me realize that I had inadvertently modified it and it couldn't send messages. It was a me issue. :)

**Comment by LewisMcMahon** [comment]
Ahh that explains it
